# Generated by Django 2.2.6 on 2019-10-18 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField()),
                ('sender_email', models.TextField()),
                ('url', models.TextField()),
                ('desc', models.TextField()),
                ('author', models.TextField()),
                ('author_url', models.TextField()),
                ('frequency', models.TextField(choices=[('D', 'daily'), ('W', 'weekly')])),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsub_url', models.TextField()),
                ('feed_count', models.IntegerField()),
                ('nwl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Newsletters')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.TextField()),
                ('ts', models.DateTimeField()),
                ('history_id', models.TextField()),
                ('is_confirmation', models.BooleanField(default=False)),
                ('nwl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Newsletters')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
