# Generated by Django 3.0.8 on 2020-07-29 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='pseudo_email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='history_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='message_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 18, 46, 9, 346957)),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='author_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='frequency',
            field=models.TextField(choices=[('D', 'daily'), ('W', 'weekly')], null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='letter',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='sender_email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usersubs',
            name='feed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubs',
            name='unsub_url',
            field=models.TextField(null=True),
        ),
    ]
