# Generated by Django 3.0.8 on 2020-08-07 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200729_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 1, 15, 42, 556499)),
        ),
    ]
