# Generated by Django 3.0.8 on 2020-08-21 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200807_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 1, 34, 42, 604599)),
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='tags',
        ),
        migrations.AddField(
            model_name='newsletters',
            name='tags',
            field=models.ManyToManyField(to='web.Tags'),
        ),
    ]
