# Generated by Django 3.0.8 on 2020-08-28 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200821_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletters',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 6, 9, 14, 694915)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.TextField(default='', unique=True),
        ),
    ]
