# Generated by Django 3.0.8 on 2020-08-28 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200828_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 6, 59, 22, 211013)),
        ),
    ]
