# Generated by Django 3.0.8 on 2020-09-02 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200828_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='extra_info',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 20, 16, 19, 803310)),
        ),
    ]
