"""
Django settings for kleeppr4 project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_runtime_dir():
    return os.path.join(BASE_DIR,"runtime")


# create essential runtime dirs
for dir in ("db","logs","cache"):
    full_dir_path = os.path.join(get_runtime_dir(),dir)
    if not os.path.exists(full_dir_path):
        os.makedirs(full_dir_path)

from dotenv import load_dotenv
load_dotenv(os.path.join(get_runtime_dir(), '.env'))

for critical_env_var in ('DJANGO_EMAIL_HOST_PASSWORD','IMAP_PASSWORD','DJANGO_ALLOWED_HOST','DJANGO_DEBUG',
                         'POSTGRES_PASSWORD','STRIPE_API_SECRET','STRIPE_WEBHOOK_SECRET','STRIPE_PRICE_ID',
                         'STRIPE_API_KEY_PUBLISHABLE'):
    if not os.getenv(critical_env_var):
        raise ImproperlyConfigured(critical_env_var)
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOST").split(",")

# Application definition

INSTALLED_APPS = [
    'web.apps.WebConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'mail_templated',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kleeppr4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kleeppr4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DEPRECATED_DATABASES_OLD = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(get_runtime_dir(),"db",'db.sqlite3'),
    },
    'OPTIONS': {
        'timeout':5000
    },

}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'TEST': {
            'NAME':'kleeppr_test'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR,"static")
STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = 'feed'
LOGOUT_REDIRECT_URL = 'login'

EMAIL_HOST="mail.kleeppr.com"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER="sandeep@kleeppr.com"
EMAIL_HOST_PASSWORD=os.getenv("DJANGO_EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL="Kleeppr Support <noreply@kleeppr.com>"

NOTIFICATION_TO_EMAIL=os.getenv("NOTIFICATION_TO_EMAIL", "hello@kleeppr.com")

WELCOME_FROM_EMAIL = 'Kleeppr Support <hello@kleeppr.com>'

PASSWORD_RESET_TIMEOUT_DAYS=1

IMAP_HOST="mail.kleeppr.com"
IMAP_PASSWORD=os.getenv("IMAP_PASSWORD")
IMAP_USER_PREFIX="u"
CACHE_PATH= os.path.join(get_runtime_dir(),"cache")

APPID_MAIL_SERVER_DOMAIN = "private.kleepprid.com"

MAIL_TEMPLATED_DOMAIN= os.getenv("MAIL_TEMPLATED_DOMAIN")

if not MAIL_TEMPLATED_DOMAIN:
    MAIL_TEMPLATED_DOMAIN = "https://kleeppr.com"


STRIPE_API_SECRET = os.getenv('STRIPE_API_SECRET')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
STRIPE_PRICE_ID = os.getenv('STRIPE_PRICE_ID')
STRIPE_API_KEY_PUBLISHABLE = os.getenv('STRIPE_API_KEY_PUBLISHABLE')


LOGGING = {

    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{ip} {user} {asctime} {method} {path} {scheme} {session_id} [{message}]',
            'style': '{',
        },
        'feeder': {
            'format' : '{levelname} {asctime} {process:d} {message}',
            'style': '{',
        }
    },
    'filters': {
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'file-django' : {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join( get_runtime_dir(),'logs','django.log'),

        },
        'file-app' : {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join( get_runtime_dir(),'logs','app.log'),
            'formatter' : 'verbose'
        },
        'file-feeder' : {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join( get_runtime_dir(),'logs','feeder.log'),
            'formatter' : 'feeder',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console','file-django'],
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console','file-django'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console','file-django'],
            'level': 'INFO',
            'propagate': False,
        },
        'app': {
            'handlers': ['file-app'],
            'level':'INFO',
            'propagate':False
        },
        'feeder': {
            'handlers': ['file-feeder'],
            'level':'INFO',
            'propagate':False
        }
    }
}
